version: "3.9"
services:
  db:
    container_name: Data_Base
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: converter_app
    volumes:
      - type: volume
        source: api-postgres-volume
        target: /var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
  converter:
    container_name: Converter_App
    build:
      context: ./Currency_converter
    links:
      - "db:db"
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  api-postgres-volume: